### ISSUE TITLE
Quest: Red Silk Bandanas

### ISSUE THREAD

**Issue by Rythex** [ProjektEredar/Vanilla_Bugtracker#11]
Späherin Riell ( http://db.vanillagaming.org/?npc=820 ) sollte die Quest Red Silk Bandanas ( http://db.vanillagaming.org/?quest=214 ) haben. Leider ist die Quest einfach nicht da

**Comment by ProjektEredar** [comment]
Hast du die pre Quest abgeschlossen?
http://db.vanillagaming.org/?quest=153
